# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(855, 579)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TestButton = QtWidgets.QPushButton(self.centralwidget)
        self.TestButton.setGeometry(QtCore.QRect(540, 169, 71, 71))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.TestButton.setFont(font)
        self.TestButton.setObjectName("TestButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 190, 181, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.queryText = QtWidgets.QTextEdit(self.centralwidget)
        self.queryText.setGeometry(QtCore.QRect(230, 170, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.queryText.setFont(font)
        self.queryText.setObjectName("queryText")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(230, 90, 291, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(630, 170, 151, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.resultText = QtWidgets.QLabel(self.centralwidget)
        self.resultText.setGeometry(QtCore.QRect(630, 220, 331, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.resultText.setFont(font)
        self.resultText.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.resultText.setObjectName("resultText")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(60, 310, 551, 211))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.btnSelect = QtWidgets.QPushButton(self.centralwidget)
        self.btnSelect.setGeometry(QtCore.QRect(80, 259, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btnSelect.setFont(font)
        self.btnSelect.setObjectName("btnSelect")
        self.btnDistinct = QtWidgets.QPushButton(self.centralwidget)
        self.btnDistinct.setGeometry(QtCore.QRect(170, 260, 81, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btnDistinct.setFont(font)
        self.btnDistinct.setObjectName("btnDistinct")
        self.btnFrom = QtWidgets.QPushButton(self.centralwidget)
        self.btnFrom.setGeometry(QtCore.QRect(260, 259, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btnFrom.setFont(font)
        self.btnFrom.setObjectName("btnFrom")
        self.btnWhere = QtWidgets.QPushButton(self.centralwidget)
        self.btnWhere.setGeometry(QtCore.QRect(350, 259, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btnWhere.setFont(font)
        self.btnWhere.setObjectName("btnWhere")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(630, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.PlainText)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.exec_result = QtWidgets.QLabel(self.centralwidget)
        self.exec_result.setGeometry(QtCore.QRect(630, 120, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exec_result.setFont(font)
        self.exec_result.setTextFormat(QtCore.Qt.PlainText)
        self.exec_result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.exec_result.setObjectName("exec_result")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.PlainText)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.table_text = QtWidgets.QLabel(self.centralwidget)
        self.table_text.setGeometry(QtCore.QRect(170, 30, 151, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.table_text.setFont(font)
        self.table_text.setTextFormat(QtCore.Qt.PlainText)
        self.table_text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.table_text.setObjectName("table_text")
        self.table_movie = QtWidgets.QPushButton(self.centralwidget)
        self.table_movie.setGeometry(QtCore.QRect(630, 370, 91, 20))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.table_movie.setFont(font)
        self.table_movie.setObjectName("table_movie")
        self.table_place = QtWidgets.QPushButton(self.centralwidget)
        self.table_place.setGeometry(QtCore.QRect(630, 430, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.table_place.setFont(font)
        self.table_place.setObjectName("table_place")
        self.table_concert = QtWidgets.QPushButton(self.centralwidget)
        self.table_concert.setGeometry(QtCore.QRect(630, 400, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.table_concert.setFont(font)
        self.table_concert.setObjectName("table_concert")
        self.table_song = QtWidgets.QPushButton(self.centralwidget)
        self.table_song.setGeometry(QtCore.QRect(630, 310, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.table_song.setFont(font)
        self.table_song.setObjectName("table_song")
        self.table_person = QtWidgets.QPushButton(self.centralwidget)
        self.table_person.setGeometry(QtCore.QRect(630, 460, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.table_person.setFont(font)
        self.table_person.setObjectName("table_person")
        self.table_album = QtWidgets.QPushButton(self.centralwidget)
        self.table_album.setGeometry(QtCore.QRect(630, 340, 91, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.table_album.setFont(font)
        self.table_album.setObjectName("table_album")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 270, 101, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.PlainText)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(70, 130, 121, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.PlainText)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.comboBox_column = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_column.setGeometry(QtCore.QRect(230, 130, 211, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.comboBox_column.setFont(font)
        self.comboBox_column.setObjectName("comboBox_column")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(440, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btnDelete.setFont(font)
        self.btnDelete.setObjectName("btnDelete")
        self.btnUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpdate.setGeometry(QtCore.QRect(530, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.btnUpdate.setFont(font)
        self.btnUpdate.setObjectName("btnUpdate")
        self.table.raise_()
        self.TestButton.raise_()
        self.label.raise_()
        self.queryText.raise_()
        self.comboBox.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.resultText.raise_()
        self.btnSelect.raise_()
        self.btnDistinct.raise_()
        self.btnFrom.raise_()
        self.btnWhere.raise_()
        self.label_6.raise_()
        self.exec_result.raise_()
        self.label_4.raise_()
        self.table_text.raise_()
        self.table_movie.raise_()
        self.table_place.raise_()
        self.table_concert.raise_()
        self.table_song.raise_()
        self.table_person.raise_()
        self.table_album.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.comboBox_column.raise_()
        self.btnDelete.raise_()
        self.btnUpdate.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 855, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TestButton.setText(_translate("MainWindow", "執行"))
        self.label.setText(_translate("MainWindow", "這裡輸入指令 :"))
        self.label_2.setText(_translate("MainWindow", "選擇方法 : "))
        self.label_3.setText(_translate("MainWindow", "查詢結果 : "))
        self.resultText.setText(_translate("MainWindow", "( 查詢結果 )"))
        self.btnSelect.setText(_translate("MainWindow", "SELECT"))
        self.btnDistinct.setText(_translate("MainWindow", "DISTINCT"))
        self.btnFrom.setText(_translate("MainWindow", "FROM"))
        self.btnWhere.setText(_translate("MainWindow", "WHERE"))
        self.label_6.setText(_translate("MainWindow", "執行結果 :"))
        self.exec_result.setText(_translate("MainWindow", "( 執行結果 )"))
        self.label_4.setText(_translate("MainWindow", "目前TABLE :"))
        self.table_text.setText(_translate("MainWindow", "SONG"))
        self.table_movie.setText(_translate("MainWindow", "MOVIE"))
        self.table_place.setText(_translate("MainWindow", "PLACE"))
        self.table_concert.setText(_translate("MainWindow", "CONCERT"))
        self.table_song.setText(_translate("MainWindow", "SONG"))
        self.table_person.setText(_translate("MainWindow", "PERSON"))
        self.table_album.setText(_translate("MainWindow", "ALBUM"))
        self.label_5.setText(_translate("MainWindow", "TABLE 列表"))
        self.label_7.setText(_translate("MainWindow", "column 內容 :"))
        self.btnDelete.setText(_translate("MainWindow", "DELETE"))
        self.btnUpdate.setText(_translate("MainWindow", "UPDATE"))
